import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Supabase CLI while the local stack is running,
    // and git-ignored (supabase/.gitignore). Without this, `npm run
    // lint` fails with ~200 errors from a scratch file nobody wrote,
    // but only on machines that happen to have run `supabase start` --
    // so the gate passes or fails for reasons unrelated to the code.
    "supabase/.temp/**",
  ]),
]);

export default eslintConfig;
