interface PactRequest {
  requestId: string
  researchQuestion: string
  context: string
  modelTier: string
  userEmail: string
}

const STOP_WORDS = new Set([
  'what','how','why','when','where','who','which','the','a','an',
  'of','in','on','to','is','are','was','were','and','or','for',
  'its','their','your','my','our','this','that','these','those',
  'does','do','did','has','have','had','can','could','would','should',
  'between','among','about','with','from','into','through','during',
  'specific','general','key','main','major','important'
])

export function generateShortSlug(researchQuestion: string): string {
  const words = researchQuestion
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOP_WORDS.has(w))
    .slice(0, 2)
    .join('-')
  return words || 'research'
}

export function generatePactFile(req: PactRequest): string {
  const now = Date.now()
  const discussionId = `discussion-${now}`
  const cellId = `${now}-${Math.random().toString(36).substring(2, 15)}`

  // Short two-word notebook name
  const notebookName = generateShortSlug(req.researchQuestion)

  // Generate system prompt from form data
  const tierInstruction = req.modelTier === 'economy'
    ? 'Provide a focused, concise analysis covering the key points efficiently.'
    : 'Provide a thorough, comprehensive analysis with detailed explanations, citations where possible, and actionable recommendations.'

  // Universal writing-style guidance, independent of model tier — added
  // after Linda Thomas's first PACT report surfaced two related gaps in
  // the same category: (1) technical terms (e.g. "null geodesics")
  // introduced in passing during a derivation, with no gloss, even though
  // the rest of the report was pitched at a teaching/conceptual level;
  // and (2) raw LaTeX shorthand (e.g. "$\sim$" for "approximately") left
  // in running prose, which — because delivered reports are Copy'd out of
  // PACT as Markdown, pasted into Obsidian, then exported to PDF — never
  // passes through an actual LaTeX renderer and shows up as literal,
  // broken-looking text. Both are style/formatting gaps, not accuracy
  // problems, and applying this to every request (not just ones that
  // signal "teaching" intent) costs an expert reader nothing while
  // meaningfully helping everyone else.
  const styleInstruction = `Write for a reader who may not be a specialist: briefly define any technical term at the moment you introduce it, even in the middle of a derivation or proof, rather than assuming prior familiarity.

Do not use LaTeX shorthand (e.g. $\\sim$) as a substitute for ordinary words in prose — write "approximately" or use a plain ~ character instead. Reserve LaTeX exclusively for genuine standalone equations, written with proper spacing so they render correctly in Markdown.

Present all derivations and explanations as clean, finished reasoning. Do not narrate your own reconsideration, self-correction, or false starts (e.g. "Wait — let me be more careful," "Actually, let's reconsider") — work through the reasoning internally and present only the final, correct derivation.`

  const contextSection = req.context
    ? `\n\nUser context: ${req.context}`
    : ''

  const systemPrompt = `You are a structured research specialist conducting a PACT research session for ${req.userEmail}.

Research topic: ${req.researchQuestion}${contextSection}

${tierInstruction} Organize findings clearly with headings, use evidence-based sources, and structure the response so it can be exported as a professional PDF report.

${styleInstruction}`

  // Build the prompt text for the first cell
  const promptText = req.context
    ? `${req.researchQuestion}\n\nAdditional context: ${req.context}`
    : req.researchQuestion

  const pactExport = {
    version: 1,
    exportedAt: now,
    notebook: {
      name: notebookName,
      systemPrompt: systemPrompt,
      executionMode: 'index',
      // Every notebook generated by the web app is, by definition, a
      // customer request — this is the one value pact-react-v3 reserves
      // exclusively for web-sourced notebooks (never manually selectable
      // in its own New Notebook dialog). Routes exports into
      // PACT-Exports/user-requests/... instead of falling into uncategorized.
      category: 'user-requests',
    },
    discussions: [
      {
        id: discussionId,
        name: 'Research Question',
        createdAt: now,
        totalTimeMs: 0,
      },
    ],
    cells: [
      {
        id: cellId,
        discussionId: discussionId,
        parentId: null,
        promptText: promptText,
        response: '',
        model: req.modelTier === 'economy' ? 'claude-haiku' : 'claude-sonnet',
        cellType: 'user',
        createdAt: now,
      },
    ],
  }

  return JSON.stringify(pactExport, null, 2)
}
