interface PactRequest {
  requestId: string
  researchQuestion: string
  context: string
  modelTier: string
  userEmail: string
}

const STOP_WORDS = new Set([
  'what','how','why','when','where','who','which','the','a','an',
  'of','in','on','to','is','are','was','were','and','or','for',
  'its','their','your','my','our','this','that','these','those',
  'does','do','did','has','have','had','can','could','would','should',
  'between','among','about','with','from','into','through','during',
  'specific','general','key','main','major','important'
])

export function generateShortSlug(researchQuestion: string): string {
  const words = researchQuestion
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOP_WORDS.has(w))
    .slice(0, 2)
    .join('-')
  return words || 'research'
}

export function generatePactFile(req: PactRequest): string {
  const now = Date.now()
  const discussionId = `discussion-${now}`
  const cellId = `${now}-${Math.random().toString(36).substring(2, 15)}`

  // Short two-word notebook name
  const notebookName = generateShortSlug(req.researchQuestion)

  // Generate system prompt from form data
  const tierInstruction = req.modelTier === 'economy'
    ? 'Provide a focused, concise analysis covering the key points efficiently.'
    : 'Provide a thorough, comprehensive analysis with detailed explanations, citations where possible, and actionable recommendations.'

  const contextSection = req.context
    ? `\n\nUser context: ${req.context}`
    : ''

  const systemPrompt = `You are a structured research specialist conducting a PACT research session for ${req.userEmail}.

Research topic: ${req.researchQuestion}${contextSection}

${tierInstruction} Organize findings clearly with headings, use evidence-based sources, and structure the response so it can be exported as a professional PDF report.`

  // Build the prompt text for the first cell
  const promptText = req.context
    ? `${req.researchQuestion}\n\nAdditional context: ${req.context}`
    : req.researchQuestion

  const pactExport = {
    version: 1,
    exportedAt: now,
    notebook: {
      name: notebookName,
      systemPrompt: systemPrompt,
      executionMode: 'index',
      // Every notebook generated by the web app is, by definition, a
      // customer request — this is the one value pact-react-v3 reserves
      // exclusively for web-sourced notebooks (never manually selectable
      // in its own New Notebook dialog). Routes exports into
      // PACT-Exports/user-requests/... instead of falling into uncategorized.
      category: 'user-requests',
    },
    discussions: [
      {
        id: discussionId,
        name: 'Research Question',
        createdAt: now,
        totalTimeMs: 0,
      },
    ],
    cells: [
      {
        id: cellId,
        discussionId: discussionId,
        parentId: null,
        promptText: promptText,
        response: '',
        model: req.modelTier === 'economy' ? 'claude-haiku' : 'claude-sonnet',
        cellType: 'user',
        createdAt: now,
      },
    ],
  }

  return JSON.stringify(pactExport, null, 2)
}
